name: dart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  duration_button: ^1.0.0
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  provider: ^6.1.2
  tuple: ^2.0.2
  collection: ^1.18.0
  path_provider: ^2.1.2

dependency_overrides:
  path_provider_android: ^2.0.33


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/