name: dart
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  duration_button: ^1.0.0
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  provider: ^6.1.2
  tuple: ^2.0.2
  collection: ^1.18.0
  path_provider: ^2.1.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  hrk_flutter_test_batteries: ^1.2.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf